refactor code

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -103,7 +103,7 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Clean ~/.cache/matlab_ci before first install
+          name: Clean cache directory before first install
           command: rm -rf $HOME/.cache/matlab_ci
           shell: bash
       - matlab/install:
@@ -114,24 +114,21 @@ jobs:
           command: |
             set -e
             ls -al "$HOME/.cache/matlab_ci/matlab_root/bin/matlab" || {
-            echo "Missing MATLAB binary at expected cache path!"
-            exit 1
+              echo "Missing MATLAB binary at expected cache path!"
+              exit 1
             }
-
             ls -al "$HOME/.cache/matlab_ci/mpm/mpm"* || {
               echo "MPM not found in cache!"
               exit 1
             }
-
             ls -al "$HOME/.cache/matlab_ci/matlab-batch/matlab-batch"* || {
               echo "MATLAB Batch not found in cache!"
               exit 1
             }
-
             echo "All expected files found in cache."
           shell: bash
       - matlab/run-command:
-          command: version  
+          command: version
 
   integration-test-run-command:
     parameters:
